### ISSUE TITLE
Proposal: Promote events

### ISSUE THREAD

**Issue by FranciscoAmado** [iOS-Goodies/iOS-Goodies#1125]
Just dropping an idea here.
Since this is a Newsletter built mostly with content suggested by the community, would be interesting to also accept free and variadic events/meetups.

I can give you an example for context: This week we're having our [first Cocoaheads Porto](https://www.meetup.com/pt-BR/CocoaHeads-Porto/events/247413496/) and since it's something that never happened before would have been great to feature/showcase this event in the last week newsletter.

I believe, with some rules, this could be a great way to promote early/unknown local events.

Thanks!

**Comment by mariusc** [comment]
Hi! Thanks for the suggestion. 

This is actually very similar to something that I've been thinking about recently. I mostly had conferences in mind, local meetups are a bit different. With regards to conferences, if we are to mention them in the newsletter, those will either have to be sponsored messages, or it should be some other kind of partnership (we'll probably have an example of that in 1.5 months 😉)

Regarding free events, like all the local CocoaHeads (and similar) meetups, since they are local events, they won't be of interest for the majority of the subscribers, so there will be many people reading something that's not really suitable for them, compared to the few ones who are actually in that area and for which that message can make a difference. As a concrete example, I'm not sure the readers from Australia would find much value in knowing about CocoaHeads Porto. It's only people from Portugal who would probably be interested in CocoaHeads Porto.

Another issue with promoting CocoaHeads-like local events is the fact that they are recurring events. If we promote all the events, I think there would be too many. And which one should we promote? The first one? The one after a long break? The one with "famous" speakers? It seems like it's hard to draw a line somewhere.

So quick **TL;DR**: conferences - ok via sponsored links or partnerships; local events: - I'd rather not do it.

Of course, this is just my opinion, and with the right arguments (or counterarguments to my concerns) I can be persuaded :)

**Comment by LisaDziuba** [comment]
@FranciscoAmado, we have an idea to make a newsletter with all cool events now. 
Feel free to DM me on Twitter :)

**Comment by FranciscoAmado** [comment]
> since they are local events, they won't be of interest for the majority of the subscribers

@mariusc You're right. I was only thinking on promoting the first edition of new meetups, even if they're local.
But I understand that it can be weird for someone to read about an event happening in a completely different Country.

Great to see we'll be expanding to conferences 👍🏻

@LisaDziuba I'll keep an eye on that then 😄

**Comment by rbarbosa** [comment]
Hi all!
I understand @FranciscoAmado idea, but I agree with @mariusc points. I think it would create some noise around the goal of iOS-Goodies newsletter.
However, and as @LisaDziuba seems to be working, it seems a good idea for a specif newsletter.

**Comment by FranciscoAmado** [comment]
Thanks for the opinions 👍
