### ISSUE TITLE
Expanding the Business category or introducing a new one

### ISSUE THREAD

**Issue by mariusc** [iOS-Goodies/iOS-Goodies#1126]
Of all the categories we have, I think Business is the one with the least number of links. Or at least, for me, it's the hardest to find good content for (most likely because I'm not looking in the right places - I'm an iOS dev and follow mostly tech and dev stuff).

At the same time, every now and then I stumble over articles like http://martiancraft.com/blog/2017/11/rookie-mistakes/ or the ones in https://www.swiftbysundell.com/meta/, or similar, focusing on productivity, and growth as a developer. 
The description of the Business section says

> Business - These articles should help the typical developer to understand how business is conducted. This could be related to the App store ecosystem, or how-to run your business as an indie dev, App marketing, etc. It can also be related about your experience while working at some company, what you liked, and what you didn't like.

That doesn't really cover the type of articles I mentioned above, but it's still the most appropriate section to put them (compared to the others). 

I'm wondering if we should rename business into "Business and `<something>`" - not really sure what that `<something>` should be: career? personal growth? developer hapiness? Or if we should make a new category for those kind of articles.

@rbarbosa @dkhamsing @LisaDziuba @FranciscoAmado and all other contributors, I'd be curious to hear your opinion on this :)

**Comment by LisaDziuba** [comment]
1. 😑 I think, there are several issues with business articles:
- they have **too many banners** as most of them are written by marketing companies or pure marketers. I try not to share such articles because pop-ups & sign-up forms kill me.
- the good marketing or business articles are written by indie devs who **do not write so often**. For example, my favorite writer, [Dan Counsell](https://dancounsell.com/2017/09/09/how-to-get-press-coverage-for-your-app/), publishes one article monthly. Under the Radar, which is pretty good too, publishes pure iOS-related podcasts not every week too. So it's simply not enough content.

2. 🤔 On the other hand, we can see many good articles with **general advice on productivity and good habits**. Those articles are targeted on developers in general. However, some of them are too fluffy ("blah-blah-blah" articles). For example, I mean something from Signal v. Noise or freeCodeCamp Medium blogs. You know, John Sundell doesn't write productivity articles weekly too :) So we can add some of those articles to the Business section, but they will need extra editors attention to cut the "bla-bla" content.

3. 👌 Career articles are pretty cool, but I'm not sure how often they are published. Also, should it be a general career advice or iOS-specific? I can recall only several good articles on getting a job as iOS developer, so it's not something we can find weekly.

**The only solution I see is to add all these categories to the Business section**, so we will have enough fresh content weekly. What others think?

**Comment by LisaDziuba** [comment]
Maybe call it **Soft Skills**

**Comment by fbara** [comment]
I'm fine with naming it 'Business/Career' or, as @LisaDziuba suggested, 'Soft Skills'.

**Comment by rbarbosa** [comment]
Here is my opinion on this subject.

I agree that sometimes we find a good article that is hard to categorise it.
I think that the question we should make when trying to see where the article belongs is, in the end, if its root is related to business for this case. That connection sometimes doesn't seem obvious, but if we look from another prism, it may fit in it - Business. Let's take the example of productive tips.  In the beginning, we are tempted to think that it's not suited for that category,  but if we think that a productive tip, for any indie developer could represent an improvement for what she or he is doing, regarding time and money, then this is clearly a Business subject. To be honest, this is also for any developer.

In some point, I agree with Lisa when she says that business articles are mostly written by marketing companies or marketers.
Personally, I don't have problems with articles written by those persons as long as I consider that it brings value to someone. The pop-ups and sing-ups are similar to what we find in with articles related to code or UX/UI. This same applies to articles considered fluffy. There are too many about code and UX/UI that, in the end, either the juice is none, or it was already written and doesn't bring anything new.
To be honest, I love articles published in Signal v. Noise'. Some of them are pure gold, and if they aren't of the best persons to write about business, then I don't know who might be. I could include here anything said or written by Gary Vaynerchuck.

For me, we shouldn't rename this section. At most, add some keyword: Business and [?].
If there's an article that isn't related to any of the current categories, but the person who submitted it thinks it makes sense, or it brings value or any other reason, then we can create a section for that (sometimes we used "One more thing") or add little text introducing it.

Finding great articles, on any subject, is hard. It becomes even harder when we filtered them by date (2 weeks old).
We shouldn't be worried if in some week we just found one or two for any category. It is what it is...
For instance, when Rui Peres and Tiago Almeida were the curators, they placed a limit of five articles for each section, and they would narrow down until they achieve that number, of course, following they own criteria.

**Comment by mariusc** [comment]
Thanks all for contributing with ideas and opinions, that's the best part of a newsletter driven by the community :)

It seems that the general opinion is that we don't need another category and that all those articles fit into the Business one. And to make it more clear, we can add another keyword to it. 

Let's try Business/Career for now and see how that goes :). If there are no objections, I'll update the contributing guidelines with the new name and a refreshed description tomorrow.
