### ISSUE TITLE
Missing article in Week329

### ISSUE THREAD

**Issue by serek8** [iOS-Goodies/iOS-Goodies#1887]
Hi, I have noticed that you missed out "A security review of 1,300 AppStore applications" on  [ios-goodies.com](https://ios-goodies.com/). It's was approved to the master branch but does not appear on the website. Can you add it to the next week release?

**Comment by mariusc** [comment]
Hi! Not everything that’s in the GitHub repo will be automatically in the newsletter, the links go through a curation process. There were many interesting links this week and I had to cut some of them from the newsletter. In the particular case of your article, the main reason was that I couldn’t read it without creating a medium account (I think it’s a premium article, or something like that. Not sure, Medium changes quite often. It has a star next to the author). I try to avoid including articles that force the users to create an account in order to read them. 
Generally we don’t take resubmissions, but if you can make the article available for people without a medium account, please submit it for next week’s edition and I’d be happy to consider it.

**Comment by serek8** [comment]
Thanks for letting me know about the problems with Medium. I wan't aware of it. I moved the article to another website, please have a look at my article.
PR: https://github.com/iOS-Goodies/iOS-Goodies/pull/1888
